# Launches a Factorio dedicated server (headless host) with RCON enabled,
# using a *separate* write-data directory so it never fights the GUI client
# for the .lock file in %APPDATA%\Factorio.
#
# First run: creates .factorio-server/ inside the repo, junctions the
# npc_mcp mod into its mods dir, and generates a fresh save if none exists.
# Subsequent runs: just relaunches the server using the existing save.
#
# Then start your normal Factorio GUI client (steam) and connect to
# 127.0.0.1 via Multiplayer -> Connect to address.

[CmdletBinding()]
param(
    [string]$FactorioExe = 'C:\Program Files (x86)\Steam\steamapps\common\Factorio\bin\x64\factorio.exe',
    [string]$SaveName    = 'npc-world',
    [int]$RconPort       = 27015,
    [string]$RconPassword,  # falls back to .env RCON_PASSWORD
    [switch]$Fresh          # delete the existing save and regenerate
)

$ErrorActionPreference = 'Stop'

$repoRoot   = Split-Path -Parent $PSScriptRoot
$serverRoot = Join-Path $repoRoot '.factorio-server'
$serverMods = Join-Path $serverRoot 'mods'
$serverSaves= Join-Path $serverRoot 'saves'
$serverCfgD = Join-Path $serverRoot 'config'
$serverCfg  = Join-Path $serverCfgD  'config.ini'
$savePath   = Join-Path $serverSaves "$SaveName.zip"
$modSource  = Join-Path $repoRoot 'mod\npc_mcp'
$dataDir    = Join-Path (Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $FactorioExe))) 'data'

if (-not (Test-Path $FactorioExe)) { throw "Factorio not found at: $FactorioExe (pass -FactorioExe)" }
if (-not (Test-Path $modSource))   { throw "Mod source not found: $modSource" }
if (-not (Test-Path $dataDir))     { throw "Factorio data dir not found: $dataDir" }

# --- ensure server write-data dir layout --------------------------------------
foreach ($d in $serverRoot, $serverMods, $serverSaves, $serverCfgD) {
    if (-not (Test-Path $d)) { New-Item -ItemType Directory -Path $d | Out-Null }
}

# Custom config.ini: redirects Factorio's write-data away from %APPDATA%\Factorio
# so the dedicated server doesn't fight the GUI client for the .lock file.
$cfgContent = @"
; auto-generated by scripts/start-factorio-server.ps1 - safe to delete
use-system-read-write-data-directories=false
[path]
read-data=$dataDir
write-data=$serverRoot
"@
Set-Content -LiteralPath $serverCfg -Value $cfgContent -Encoding ASCII

# Junction the mod into the server's mods dir (idempotent).
# PowerShell 5.1's `New-Item -ItemType Junction` silently creates an empty
# real directory if the target path doesn't resolve cleanly, which leaves
# Factorio loading a checksum-0 stub mod. Use cmd's mklink /J instead and
# tear down any prior empty/broken folder first.
$modLink = Join-Path $serverMods 'npc_mcp'
if (Test-Path $modLink) {
    $item = Get-Item $modLink -Force
    $isJunction = $item.Attributes.ToString().Contains('ReparsePoint')
    $linkOk = $isJunction -and (Test-Path (Join-Path $modLink 'info.json'))
    if (-not $linkOk) {
        Write-Host "Replacing broken mod link at: $modLink"
        Remove-Item -LiteralPath $modLink -Recurse -Force
    }
}
if (-not (Test-Path $modLink)) {
    Write-Host "Junctioning mod: $modLink -> $modSource"
    & cmd /c mklink /J "`"$modLink`"" "`"$modSource`"" | Out-Null
    if (-not (Test-Path (Join-Path $modLink 'info.json'))) {
        throw "mod junction failed: $modLink has no info.json after mklink"
    }
}

# Enable the mod in the server's mod-list.json.
$modList = Join-Path $serverMods 'mod-list.json'
$modListContent = @'
{
  "mods": [
    { "name": "base",    "enabled": true },
    { "name": "npc_mcp", "enabled": true }
  ]
}
'@
Set-Content -LiteralPath $modList -Value $modListContent -Encoding UTF8 -NoNewline

# server-settings.json: critical to disable auto_pause, otherwise the sim
# FREEZES whenever zero players are connected -- which is the normal state
# when Claude drives the NPC headlessly. With auto_pause=true, RCON commands
# still execute but each one advances only ~1 tick, making it look like the
# game only progresses when you poll. We don't want that.
$serverSettings = Join-Path $serverRoot 'server-settings.json'
if (-not (Test-Path $serverSettings)) {
    $exampleSettings = Join-Path $dataDir 'server-settings.example.json'
    if (Test-Path $exampleSettings) {
        Copy-Item -LiteralPath $exampleSettings -Destination $serverSettings
    } else {
        # Minimal fallback if the example file is missing.
        Set-Content -LiteralPath $serverSettings -Encoding UTF8 -Value '{}'
    }
}
# Force auto_pause=false and no_auto_pause_when_players_connect=false via a
# Python one-liner (PS 5.1 ConvertTo-Json is unreliable for Factorio configs).
$py = (Get-Command python -ErrorAction SilentlyContinue).Source
if ($py) {
    $pyScript = @"
import json, sys
p = r'$serverSettings'
with open(p, 'r', encoding='utf-8-sig') as f: d = json.load(f)
d['auto_pause'] = False
d.setdefault('name', 'factorio_npc_mcp')
d.setdefault('description', 'Headless server for the NPC MCP. auto_pause disabled so the sim runs without players connected.')
with open(p, 'w', encoding='utf-8', newline='\n') as f: json.dump(d, f, indent=2, ensure_ascii=False)
"@
    & $py -c $pyScript
} else {
    Write-Warning "python not on PATH; couldn't patch server-settings.json. Manually set auto_pause=false in $serverSettings."
}

# --- resolve RCON password ----------------------------------------------------
if (-not $RconPassword) {
    $envFile = Join-Path $repoRoot '.env'
    if (Test-Path $envFile) {
        $m = Select-String -Path $envFile -Pattern '^RCON_PASSWORD=(.*)$'
        if ($m) { $RconPassword = $m.Matches.Groups[1].Value }
    }
}
if (-not $RconPassword) { throw "No RCON password (pass -RconPassword or set RCON_PASSWORD in .env)" }

# --- create save if missing (or if -Fresh) ------------------------------------
if ($Fresh -and (Test-Path $savePath)) {
    Write-Host "Deleting existing save: $savePath"
    Remove-Item -LiteralPath $savePath -Force
}
if (-not (Test-Path $savePath)) {
    Write-Host "Generating new save: $savePath"
    & $FactorioExe --config $serverCfg --create $savePath
    if ($LASTEXITCODE -ne 0) { throw "save generation failed ($LASTEXITCODE)" }
}

# --- launch -------------------------------------------------------------------
Write-Host ""
Write-Host "Starting Factorio dedicated server:"
Write-Host "  save        : $savePath"
Write-Host "  write-data  : $serverRoot"
Write-Host "  config      : $serverCfg"
Write-Host "  RCON listen : 127.0.0.1:$RconPort"
Write-Host ""
Write-Host "When the log shows 'changing state from(CreatingGame) to(InGame)',"
Write-Host "open Factorio GUI -> Multiplayer -> Connect to address -> 127.0.0.1"
Write-Host ""

& $FactorioExe `
    --config $serverCfg `
    --start-server $savePath `
    --server-settings $serverSettings `
    --rcon-bind "127.0.0.1:$RconPort" `
    --rcon-password $RconPassword
